// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated and manual changes will be
//     clobbered when the file is regenerated.
//
//     Please read more about how to change this file in
//     .github/CONTRIBUTING.md.
//
// ----------------------------------------------------------------------------

package google


func resourceComputeRegion() *schema.Resource {
	return &schema.Resource{
		Create: resourceComputeRegionCreate,
		Read: resourceComputeRegionRead,
				Update: resourceComputeRegionUpdate,
				Delete: resourceComputeRegionDelete,

		Importer: &schema.ResourceImporter{
			State: resourceComputeRegionImport,
		},

		Schema: map[string]*schema.Schema{
	"name": {
  Type: schema.TypeString,
  Optional: true,
},
	"creation_timestamp": {
  Type: schema.TypeString,
  Computed: true,
},
	"deprecated_deleted": {
  Type: schema.TypeString,
  Computed: true,
},
	"deprecated_deprecated": {
  Type: schema.TypeString,
  Computed: true,
},
	"deprecated_obsolete": {
  Type: schema.TypeString,
  Computed: true,
},
	"deprecated_replacement": {
  Type: schema.TypeString,
  Computed: true,
},
	"deprecated_state": {
  Type: schema.TypeString,
  Computed: true,
},
	"description": {
  Type: schema.TypeString,
  Computed: true,
},
	"id": {
  Type: schema.TypeInt,
  Computed: true,
},
	"zones": {
  Type: schema.TypeList,
  Computed: true,
        Elem: &schema.Schema{
      Type: schema.TypeString,
            },
  },
			"project": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
			"self_link": &schema.Schema{
				Type:     schema.TypeString,
				Computed: true,
			},
		},
	}
}

func resourceComputeRegionCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	obj := map[string]interface{}{
  "name": expandComputeRegionName(d.Get("name")),
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/regions")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Creating new Region: %#v", obj)
	res, err := Post(config, url, obj)
	if err != nil {
		return fmt.Errorf("Error creating Region: %s", err)
	}

	// Store the ID now
	id, err := replaceVars(d, config, "")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	op := &compute.Operation{}
	err = Convert(res, op)
	if err != nil {
		return err
	}

	waitErr := computeOperationWait(config.clientCompute, op, project, "Creating Region")
	if waitErr != nil {
		// The resource didn't actually create
		d.SetId("")
		return waitErr
	}

	return resourceComputeRegionRead(d, meta)
}

func resourceComputeRegionRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/regions/{{name}}")
	if err != nil {
		return err
	}

	res, err := Get(config, url)
	if err != nil {
		return handleNotFoundError(err, d, fmt.Sprintf("ComputeRegion %q", d.Id()))
	}

  d.Set("creation_timestamp", flattenComputeRegionCreationTimestamp(res["creationTimestamp"]))
  d.Set("deprecated_deleted", flattenComputeRegionDeprecated.deleted(res["deprecated.deleted"]))
  d.Set("deprecated_deprecated", flattenComputeRegionDeprecated.deprecated(res["deprecated.deprecated"]))
  d.Set("deprecated_obsolete", flattenComputeRegionDeprecated.obsolete(res["deprecated.obsolete"]))
  d.Set("deprecated_replacement", flattenComputeRegionDeprecated.replacement(res["deprecated.replacement"]))
  d.Set("deprecated_state", flattenComputeRegionDeprecated.state(res["deprecated.state"]))
  d.Set("description", flattenComputeRegionDescription(res["description"]))
  d.Set("id", flattenComputeRegionId(res["id"]))
  d.Set("name", flattenComputeRegionName(res["name"]))
  d.Set("zones", flattenComputeRegionZones(res["zones"]))
	d.Set("self_link", res["selfLink"])
	d.Set("project", project)

	return nil
}

func resourceComputeRegionUpdate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

		obj := map[string]interface{}{
				"name": expandComputeRegionName(d.Get("name")),
			}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/regions/{{name}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Updating Region %q: %#v", d.Id(), obj)
	res, err := sendRequest(config, "PUT", url, obj)

	if err != nil {
		return fmt.Errorf("Error updating Region %q: %s", d.Id(), err)
	}
	err = Convert(res, &op)
	if err != nil {
		return err
	}

	err = computeOperationWait(config.clientCompute, &op, project, "Updating Region")
	if err != nil {
		return err
	}
	

	return resourceComputeRegionRead(d, meta)
}


func resourceComputeRegionDelete(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/regions/{{name}}")
	if err != nil {
		return err
	}

	log.Printf("[DEBUG] Deleting Region %q", d.Id())
	res, err := Delete(config, url)
	if err != nil {
		return fmt.Errorf("Error deleting Region %q: %s", d.Id(), err)
	}

	op := &compute.Operation{}
	err = Convert(res, op)
	if err != nil {
		return err
	}

	err = computeOperationWait(config.clientCompute, op, project, "Deleting Region")
	if err != nil {
		return err
	}

	return nil
}

func resourceComputeRegionImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	d.Set("", d.Id())
	return []*schema.ResourceData{d}, nil
}

  func flattenComputeRegionCreationTimestamp(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionDeprecated.deleted(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionDeprecated.deprecated(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionDeprecated.obsolete(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionDeprecated.replacement(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionDeprecated.state(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionDescription(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionId(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionName(v interface{}) interface{} {
  return v
}

  func flattenComputeRegionZones(v interface{}) interface{} {
  return v
}


  func expandComputeRegionName(v interface{}) interface{} {
  return v
}
