// ----------------------------------------------------------------------------
//
//     ***     AUTO GENERATED CODE    ***    AUTO GENERATED CODE     ***
//
// ----------------------------------------------------------------------------
//
//     This file is automatically generated by terraform-codegen and manual
//     changes will be clobbered when the file is regenerated.
//
//     Please read more about how to change this file in README.md and
//     CONTRIBUTING.md located at the root of this package.
//
// ----------------------------------------------------------------------------

package google

import (
	"fmt"

	"github.com/hashicorp/terraform/helper/schema"
	compute "google.golang.org/api/compute/v1"
)

func resourceComputeTargetSslProxy() *schema.Resource {
	return &schema.Resource{
		Create: resourceComputeTargetSslProxyCreate,
		Read:   resourceComputeTargetSslProxyRead,
		Update: resourceComputeTargetSslProxyUpdate,
		Delete: resourceComputeTargetSslProxyDelete,

		Importer: &schema.ResourceImporter{
			State: resourceComputeTargetSslProxyImport,
		},

		Schema: map[string]*schema.Schema{
			"description": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"name": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"proxy_header": {
				Type:     schema.TypeString,
				Optional: true,
			},
			"service": {
				Type:             schema.TypeString,
				Optional:         true,
				DiffSuppressFunc: compareSelfLinkOrResourceName,
			},
			"ssl_certificates": {
				Type:     schema.TypeList,
				Optional: true,
				Elem: &schema.Schema{
					Type:             schema.TypeString,
					DiffSuppressFunc: compareSelfLinkOrResourceName,
				},
			},
			"creation_timestamp": {
				Type:     schema.TypeString,
				Computed: true,
			},
			"id": {
				Type:     schema.TypeInt,
				Computed: true,
			},
			"project": &schema.Schema{
				Type:     schema.TypeString,
				Optional: true,
				Computed: true,
				ForceNew: true,
			},
		},
	}
}

func resourceComputeTargetSslProxyCreate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	obj := map[string]interface{}{
		"description":     expandComputeTargetSslProxyDescription(d.Get("description")),
		"name":            expandComputeTargetSslProxyName(d.Get("name")),
		"proxyHeader":     expandComputeTargetSslProxyProxyHeader(d.Get("proxy_header")),
		"service":         expandComputeTargetSslProxyService(d.Get("service")),
		"sslCertificates": expandComputeTargetSslProxySslCertificates(d.Get("ssl_certificates")),
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/global/targetSslProxies")
	if err != nil {
		return err
	}
	res, err := Post(config, url, obj)
	if err != nil {
		return fmt.Errorf("Error creating TargetSslProxy: %s", err)
	}

	// Store the ID now
	id, err := replaceVars(d, config, "")
	if err != nil {
		return fmt.Errorf("Error constructing id: %s", err)
	}
	d.SetId(id)

	op := &compute.Operation{}
	err = Convert(res, op)
	if err != nil {
		return err
	}

	waitErr := computeOperationWait(config.clientCompute, op, project, "Creating TargetSslProxy")
	if waitErr != nil {
		// The resource didn't actually create
		d.SetId("")
		return waitErr
	}

	return resourceComputeTargetSslProxyRead(d, meta)
}

func resourceComputeTargetSslProxyRead(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/global/targetSslProxies/{{name}}")
	if err != nil {
		return err
	}
	res, err := Get(config, url)
	if err != nil {
		return handleNotFoundError(err, d, fmt.Sprintf("ComputeTargetSslProxy %q", d.Id()))
	}

	d.Set("creation_timestamp", flattenComputeTargetSslProxyCreationTimestamp(res["creationTimestamp"]))
	d.Set("description", flattenComputeTargetSslProxyDescription(res["description"]))
	d.Set("id", flattenComputeTargetSslProxyId(res["id"]))
	d.Set("name", flattenComputeTargetSslProxyName(res["name"]))
	d.Set("proxy_header", flattenComputeTargetSslProxyProxyHeader(res["proxyHeader"]))
	d.Set("service", flattenComputeTargetSslProxyService(res["service"]))
	d.Set("ssl_certificates", flattenComputeTargetSslProxySslCertificates(res["sslCertificates"]))
	d.Set("self_link", res["selfLink"])
	d.Set("project", project)

	return nil
}

func resourceComputeTargetSslProxyUpdate(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	obj := map[string]interface{}{
		"description":     expandComputeTargetSslProxyDescription(d.Get("description")),
		"name":            expandComputeTargetSslProxyName(d.Get("name")),
		"proxyHeader":     expandComputeTargetSslProxyProxyHeader(d.Get("proxy_header")),
		"service":         expandComputeTargetSslProxyService(d.Get("service")),
		"sslCertificates": expandComputeTargetSslProxySslCertificates(d.Get("ssl_certificates")),
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/global/targetSslProxies/{{name}}")
	if err != nil {
		return err
	}
	res, err := Put(config, url, obj)
	if err != nil {
		return fmt.Errorf("Error updating TargetSslProxy %q: %s", d.Id(), err)
	}

	op := &compute.Operation{}
	err = Convert(res, op)
	if err != nil {
		return err
	}

	err = computeOperationWait(config.clientCompute, op, project, "Updating TargetSslProxy")
	if err != nil {
		return err
	}

	return resourceComputeTargetSslProxyRead(d, meta)
}

func resourceComputeTargetSslProxyDelete(d *schema.ResourceData, meta interface{}) error {
	config := meta.(*Config)

	project, err := getProject(d, config)
	if err != nil {
		return err
	}

	url, err := replaceVars(d, config, "https://www.googleapis.com/compute/v1/projects/{{project}}/global/targetSslProxies/{{name}}")
	if err != nil {
		return err
	}
	res, err := Delete(config, url)
	if err != nil {
		return fmt.Errorf("Error deleting TargetSslProxy %q: %s", d.Id(), err)
	}

	op := &compute.Operation{}
	err = Convert(res, op)
	if err != nil {
		return err
	}

	err = computeOperationWait(config.clientCompute, op, project, "Updating TargetSslProxy")
	if err != nil {
		return err
	}

	return nil
}

func resourceComputeTargetSslProxyImport(d *schema.ResourceData, meta interface{}) ([]*schema.ResourceData, error) {
	d.Set("", d.Id())
	return []*schema.ResourceData{d}, nil
}

func flattenComputeTargetSslProxyCreationTimestamp(v interface{}) interface{} {
	return v
}

func flattenComputeTargetSslProxyDescription(v interface{}) interface{} {
	return v
}

func flattenComputeTargetSslProxyId(v interface{}) interface{} {
	return v
}

func flattenComputeTargetSslProxyName(v interface{}) interface{} {
	return v
}

func flattenComputeTargetSslProxyProxyHeader(v interface{}) interface{} {
	return v
}

func flattenComputeTargetSslProxyService(v interface{}) interface{} {
	return v
}

func flattenComputeTargetSslProxySslCertificates(v interface{}) interface{} {
	return v
}

func expandComputeTargetSslProxyDescription(v interface{}) interface{} {
	return v
}

func expandComputeTargetSslProxyName(v interface{}) interface{} {
	return v
}

func expandComputeTargetSslProxyProxyHeader(v interface{}) interface{} {
	return v
}

func expandComputeTargetSslProxyService(v interface{}) interface{} {
	return v
}

func expandComputeTargetSslProxySslCertificates(v interface{}) interface{} {
	return v
}
